from salon_karola_legacy import api_appointments_today
from salon_karola_legacy import api_calendar_day
from salon_karola_legacy import api_calendar_month
from salon_karola_legacy import api_create_appointment
from salon_karola_legacy import api_move_appointment
from salon_karola_legacy import api_update_appointment
from salon_karola_legacy import calendar_view
