from salon_karola_legacy import _parse_dt_safe
from salon_karola_legacy import _safe_int
from salon_karola_legacy import normalized_phone_number
from salon_karola_legacy import phone_href
from salon_karola_legacy import rounded_duration
