from salon_karola_legacy import close_db
from salon_karola_legacy import get_db
from salon_karola_legacy import get_setting
from salon_karola_legacy import init_db
from salon_karola_legacy import set_setting
